export const categories = [
  "Beauty",
  "Fragrances",
  "Furniture",
  "Groceries",
  "Home Decoration",
  "Kitchen Accessories",
  "Laptops",
  "Mens Shirts",
  "Mens Shoes",
  "Mens Watches",
  "Mobile Accessories",
  "Motorcycle",
  "Skin Care",
  "Smartphones",
  "Sports Accessories",
  "Sunglasses",
  "Tablets",
  "Tops",
  "Vehicle",
  "Womens Bags",
  "Womens Dresses",
  "Womens Jewellery",
  "Womens Shoes",
  "Womens Watches"
]
